spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zzy0604ZZY
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.119.130
    port: 5672
    username: guest
    password: guest
name: zhouzhenyi3
env: dev
product:
  id: 234
  name: apple4
